# Travis-CI ~ https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

language: node_js

node_js: 11 # Was: 9

cache: npm

git:
  depth: 8

# install: npm ci

before_script: npm run build

# script: npm test

after_script:
  - npx eslint src/
  - ls -al dist/
  - ls -alh jsdoc/
  - git status
  - npm audit
  - npm outdated

# End.
